from __future__ import annotations

import argparse
import json
from pathlib import Path


def export_table(output: Path, *, version: str) -> None:
    from mteb import get_model_metas

    models: dict[str, int] = {}
    for meta in get_model_metas():
        name = str(getattr(meta, "name", "") or "").strip()
        max_tokens = getattr(meta, "max_tokens", None)
        try:
            tokens = int(float(max_tokens))
        except (TypeError, ValueError):
            continue
        if not name or tokens < 128:
            continue
        models[name] = tokens
    payload = {
        "format": "personalityrag.embedding_context_lengths",
        "version": version,
        "source": "MTEB ModelMeta.max_tokens; generated by tools/export_embedding_context_lengths.py",
        "models": dict(sorted(models.items(), key=lambda item: item[0].casefold())),
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export a lightweight embedding model context-length table from MTEB metadata."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1]
        / "personalityrag"
        / "resources"
        / "embedding_context_lengths.json",
    )
    parser.add_argument("--version", default="mteb-generated")
    args = parser.parse_args()
    export_table(args.output, version=args.version)


if __name__ == "__main__":
    main()
